name: flutter_chat_demo
description: This is the demo for chat app by Flutter
publish_to: 'none'

version: 1.0.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_auth: ^5.4.1
  google_sign_in: ^6.2.1
  fluttertoast: ^8.2.10
  image_picker: ^1.0.7
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^18.0.1
  photo_view: ^0.15.0
  provider: ^6.1.2
  intl: ^0.20.1
  flutter_lints: ^5.0.0
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  shared_preferences: ^2.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/

environment:
  sdk: ">=3.0.0 <4.0.0"