name: flutter_chat_demo
description: This is the demo for chat app by Flutter
publish_to: 'none'

version: 1.0.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_auth: ^5.4.1
  google_sign_in: ^6.2.1
  fluttertoast: ^8.2.10
  image_picker: ^1.0.7
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^18.0.1
  photo_view: ^0.15.0
  provider: ^6.1.2
  intl: ^0.20.1
  flutter_lints: ^5.0.0
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  shared_preferences: ^2.2.2

dependency_overrides:
  async: ^2.12.0
  boolean_selector: ^2.1.2
  characters: ^1.4.0
  clock: ^1.1.2
  collection: ^1.19.1
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  leak_tracker_flutter_testing: ^3.0.9
  matcher: ^0.12.17
  material_color_utilities: ^0.12.0
  meta: ^1.16.0
  path: ^1.9.1
  petitparser: ^6.1.0
  source_span: ^1.10.1
  stack_trace: ^1.12.1
  stream_channel: ^2.1.4
  string_scanner: ^1.4.1
  term_glyph: ^1.2.2
  test_api: ^0.7.4
  vm_service: ^15.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/

environment:
  sdk: ">=3.0.0 <4.0.0"